### ISSUE TITLE
catalogue 

### ISSUE THREAD

**Issue by Acul4321** [Unigiri-Studio/KelvinGameJam#5]
for every fish species we should quiz the average size of a fish to unlock it in the museum

**Comment by isym444** [comment]
Once you fish a fish, you get told its size, which corresponds to it's species average size

Top left hamburger / keyboard shortcut
Pause game
Don't replace entire scene tree with catalogue, just overlay it

Pause menu:
Option to quit game
Catalogue with 10 species
Underneath each plaque, text field into which you can input the average size (integer). Once you guess it, the empty plaque will then display the image of the fish.

**Comment by Acul4321** [comment]
hello, ill keep it open incase i cannot implement, but i will start redoing it and integrating it with the resources
